import type { CharacterDetail } from "@/features/character-sheet/types/character.types";

export function fullCharacterDetailFixture(
  patch: Partial<CharacterDetail> = {},
): CharacterDetail {
  return {
    id: 1,
    name: "Aldric",
    level: 5,
    proficiency_bonus: 3,
    species_name: "Human",
    background_name: "Soldier",
    starting_gold_gp: 0,
    classes: [{ name: "Fighter", level: 5 }],
    updated_at: "2026-01-01T00:00:00Z",
    is_owner: true,
    sheet_summary: {
      size: "Medium",
      speed: 30,
      current_hp: 45,
      max_hp: 45,
      temporary_hp: 0,
      death_save_successes: 0,
      death_save_failures: 0,
      heroic_inspiration: false,
      armor_class: 18,
      feats: "Tough",
      conditions: null,
    },
    abilities: [
      { ability: "STR", label: "Força", score: 16, modifier: 3 },
      { ability: "DEX", label: "Destreza", score: 14, modifier: 2 },
      { ability: "CON", label: "Constituição", score: 14, modifier: 2 },
      { ability: "INT", label: "Inteligência", score: 10, modifier: 0 },
      { ability: "WIS", label: "Sabedoria", score: 12, modifier: 1 },
      { ability: "CHA", label: "Carisma", score: 8, modifier: -1 },
    ],
    saving_throws: [
      { ability: "STR", label: "Força", modifier: 5, proficient: true },
      { ability: "CON", label: "Constituição", modifier: 4, proficient: true },
    ],
    skills: [
      {
        skill: "Athletics",
        base_attribute: "STR",
        modifier: 5,
        proficient: true,
        expertise: false,
      },
      {
        skill: "Perception",
        base_attribute: "WIS",
        modifier: 3,
        proficient: true,
        expertise: false,
      },
    ],
    passive_perception: 13,
    spell_slots: [],
    spellcasting: null,
    spellcasting_entries: [],
    weapons: [
      {
        item_id: 1,
        name: "Longsword",
        is_equipped: true,
        attack_ability: "STR",
        attack_bonus: 6,
        damage_formula: "1d8+3",
        damage_type: "Slashing",
        properties: "Versatile",
      },
    ],
    inventory: [
      {
        item_id: 1,
        name: "Longsword",
        quantity: 1,
        is_equipped: true,
        item_type: "Weapon",
        cost_gp: 15,
        weight_lb: 3,
        is_magical: false,
        weapon_category: "Martial",
        damage_die: "d8",
        die_count: 1,
        flat_bonus: null,
        damage_type: "Slashing",
        mastery_name: null,
        weapon_properties: "Versatile",
        armor_category: null,
        ac_bonus: null,
        min_strength: null,
        stealth_disadvantage: null,
        plus_dex_modifier: null,
        max_dex_bonus: null,
        is_attuned: false,
        requires_attunement: false,
        is_consumable: false,
      },
    ],
    proficiencies: [
      {
        proficiency_type: "armor",
        name: "Heavy Armor",
        tool_id: null,
        tool_category: null,
        tool_base_attribute: null,
        source_type: "class",
        source_id: 1,
      },
    ],
    known_spells: [],
    trait_options: [],
    trait_spell_choices: [],
    active_effects: [
      {
        source_type: "feat",
        source_name: "Tough",
        trait_name: null,
        effect_name: "Tough",
        is_active: true,
        duration_text: null,
        modifiers: [],
        damage_adjustments: [],
        statuses: [],
        condition_adjustments: [],
        proficiencies: [],
      },
    ],
    stat_modifiers: [
      {
        affected_stat: "max_hp",
        operation: "add",
        modifier_value: 10,
        source_name: "Tough",
        is_active: true,
      },
    ],
    traits: [
      {
        trait_id: 1,
        trait_name: "Second Wind",
        source_type: "class",
        source_name: "Fighter",
        level_required: 1,
      },
    ],
    resources: [
      {
        trait_id: 1,
        resource_key: "second-wind",
        name: "Second Wind",
        max_uses: 1,
        used_uses: 0,
        reset_on: "Short Rest",
      },
    ],
    ...patch,
  };
}
