import type { CharacterDetail } from "@/features/character-sheet/types/character.types";

export function fullCharacterDetailFixture(
  patch: Partial<CharacterDetail> = {},
): CharacterDetail {
  return {
    id: 1,
    name: "Aldric",
    level: 5,
    proficiency_bonus: 3,
    species_name: "Human",
    background_name: "Soldier",
    starting_gold_gp: 0,
    classes: [{ name: "Fighter", level: 5 }],
    updated_at: "2026-01-01T00:00:00Z",
    is_owner: true,
    sheet_summary: {
      size: "Medium",
      speed: 30,
      current_hp: 45,
      max_hp: 45,
      temporary_hp: 0,
      death_save_successes: 0,
      death_save_failures: 0,
      heroic_inspiration: false,
      armor_class: 18,
      feats: "Tough",
      conditions: null,
    },
    abilities: [
      { ability: "STR", label: "Força", score: 16, modifier: 3 },
      { ability: "DEX", label: "Destreza", score: 14, modifier: 2 },
      { ability: "CON", label: "Constituição", score: 14, modifier: 2 },
      { ability: "INT", label: "Inteligência", score: 10, modifier: 0 },
      { ability: "WIS", label: "Sabedoria", score: 12, modifier: 1 },
      { ability: "CHA", label: "Carisma", score: 8, modifier: -1 },
    ],
    saving_throws: [
      { ability: "STR", label: "Força", modifier: 5, proficient: true },
      { ability: "CON", label: "Constituição", modifier: 4, proficient: true },
    ],
    skills: [
      {
        skill: "Athletics",
        base_attribute: "STR",
        modifier: 5,
        proficient: true,
        expertise: false,
      },
      {
        skill: "Perception",
        base_attribute: "WIS",
        modifier: 3,
        proficient: true,
        expertise: false,
      },
    ],
    passive_perception: 13,
    spell_slots: [],
    spellcasting: null,
    spellcasting_entries: [],
    weapons: [
      {
        item_id: 1,
        name: "Longsword",
        is_equipped: true,
        attack_ability: "STR",
        attack_bonus: 6,
        damage_formula: "1d8+3",
        damage_type: "Slashing",
        properties: "Versatile",
      },
    ],
    inventory: [
      {
        item_id: 1,
        name: "Longsword",
        quantity: 1,
        is_equipped: true,
        item_type: "Weapon",
        cost_gp: 15,
        weight_lb: 3,
        is_magical: false,
        weapon_category: "Martial",
        damage_die: "d8",
        die_count: 1,
        flat_bonus: null,
        damage_type: "Slashing",
        mastery_name: "Sap",
        weapon_properties: "Versatile",
        armor_category: null,
        ac_bonus: null,
        min_strength: null,
        stealth_disadvantage: null,
        plus_dex_modifier: null,
        max_dex_bonus: null,
        is_attuned: false,
        requires_attunement: false,
        is_consumable: false,
      },
      {
        item_id: 2,
        name: "Ring of Protection",
        quantity: 1,
        is_equipped: false,
        item_type: "Item",
        cost_gp: null,
        weight_lb: null,
        is_magical: true,
        weapon_category: null,
        damage_die: null,
        die_count: null,
        flat_bonus: null,
        damage_type: null,
        mastery_name: null,
        weapon_properties: null,
        armor_category: null,
        ac_bonus: null,
        min_strength: null,
        stealth_disadvantage: null,
        plus_dex_modifier: null,
        max_dex_bonus: null,
        is_attuned: true,
        requires_attunement: true,
        is_consumable: false,
      },
    ],
    proficiencies: [
      {
        proficiency_type: "armor",
        name: "Heavy Armor",
        tool_id: null,
        tool_category: null,
        tool_base_attribute: null,
        source_type: "class",
        source_id: 1,
      },
    ],
    known_spells: [],
    trait_options: [
      {
        trait_id: 10,
        trait_name: "Fighting Style",
        option_group: "default",
        choice_count: 1,
        is_required: true,
        selection_key: "default",
        trait_option_id: 20,
        option_name: "Defense",
        option_description: "+1 CA com armadura equipada.",
        option_skill_name: null,
        option_tool_name: null,
        option_spell_list_name: null,
        source_type: "class",
        source_id: 1,
        notes: null,
      },
    ],
    trait_spell_choices: [],
    active_effects: [
      {
        source_type: "feat",
        source_name: "Tough",
        trait_name: null,
        effect_name: "Tough",
        is_active: true,
        duration_text: null,
        modifiers: [{ affected_stat: "max_hp", operation: "add", modifier_value: 10 }],
        damage_adjustments: [
          { damage_type: "Fire", adjustment_type: "resistance", scope_text: null },
        ],
        statuses: [{ status: "Blessed", duration_text: "1 minute", scope_text: null }],
        condition_adjustments: [],
        proficiencies: [],
      },
      {
        source_type: "species",
        source_name: "Human",
        trait_name: "Skillful",
        effect_name: "Skillful",
        is_active: true,
        duration_text: null,
        modifiers: [],
        damage_adjustments: [],
        statuses: [],
        condition_adjustments: [],
        proficiencies: [
          {
            name: null,
            tool: null,
            notes: "Choose one skill proficiency.",
            skill: null,
            language: null,
            choice_count: 1,
            tool_category: null,
            proficiency_type: "skill",
            requires_choice: true,
          },
        ],
      },
    ],
    stat_modifiers: [
      {
        affected_stat: "max_hp",
        operation: "add",
        modifier_value: 10,
        source_name: "Tough",
        is_active: true,
      },
    ],
    traits: [
      {
        trait_id: 1,
        trait_name: "Second Wind",
        source_type: "class",
        source_name: "Fighter",
        level_required: 1,
      },
    ],
    resources: [
      {
        trait_id: 1,
        resource_key: "second-wind",
        name: "Second Wind",
        max_uses: 1,
        used_uses: 0,
        reset_on: "Short Rest",
      },
    ],
    character_feats: [
      {
        feat_id: 5,
        name: "Tough",
        category: "Origin",
        source_type: "background",
        source_id: 2,
        selection_key: null,
        notes: null,
      },
    ],
    ...patch,
  };
}

export function wizardCharacterFixture(
  patch: Partial<CharacterDetail> = {},
): CharacterDetail {
  return fullCharacterDetailFixture({
    name: "Elara",
    level: 5,
    classes: [{ name: "Wizard", level: 5 }],
    species_name: "Elf",
    background_name: "Sage",
    spellcasting: {
      class_name: "Wizard",
      progression_type: "full",
      slot_recovery: "Long Rest",
      spellcasting_ability: "INT",
    },
    spellcasting_entries: [
      {
        class_id: 8,
        class_name: "Wizard",
        class_level: 5,
        spellcasting_ability: "INT",
        spell_attack_bonus: 7,
        spell_save_dc: 15,
      },
    ],
    spell_slots: [
      { slot_level: 1, max_slots: 4, used_slots: 1 },
      { slot_level: 2, max_slots: 3, used_slots: 0 },
      { slot_level: 3, max_slots: 2, used_slots: 0 },
    ],
    known_spells: [
      {
        spell_id: 1,
        name: "Fire Bolt",
        level: 0,
        school: "Evocation",
        casting_time: "1 action",
        range_text: "120 feet",
        components: "V,S",
        material_component: null,
        duration_text: "Instantaneous",
        requires_concentration: false,
        requires_ritual: false,
        save_attribute: null,
        attack_type: "ranged",
        source_type: "class",
        is_prepared: false,
        always_prepared: false,
      },
      {
        spell_id: 2,
        name: "Magic Missile",
        level: 1,
        school: "Evocation",
        casting_time: "1 action",
        range_text: "120 feet",
        components: "V,S",
        material_component: null,
        duration_text: "Instantaneous",
        requires_concentration: false,
        requires_ritual: false,
        save_attribute: null,
        attack_type: null,
        source_type: "class",
        is_prepared: true,
        always_prepared: false,
      },
      {
        spell_id: 3,
        name: "Shield",
        level: 1,
        school: "Abjuration",
        casting_time: "1 reaction",
        range_text: "Self",
        components: "V,S",
        material_component: null,
        duration_text: "1 round",
        requires_concentration: false,
        requires_ritual: false,
        save_attribute: null,
        attack_type: null,
        source_type: "class",
        is_prepared: true,
        always_prepared: false,
      },
      {
        spell_id: 4,
        name: "Detect Magic",
        level: 1,
        school: "Divination",
        casting_time: "1 action",
        range_text: "Self",
        components: "V,S",
        material_component: null,
        duration_text: "Concentration, up to 10 minutes",
        requires_concentration: true,
        requires_ritual: true,
        save_attribute: null,
        attack_type: null,
        source_type: "class",
        is_prepared: false,
        always_prepared: false,
      },
      {
        spell_id: 5,
        name: "Mage Armor",
        level: 1,
        school: "Abjuration",
        casting_time: "1 action",
        range_text: "Touch",
        components: "V,S,M",
        material_component: "piece of cured leather",
        duration_text: "8 hours",
        requires_concentration: false,
        requires_ritual: false,
        save_attribute: null,
        attack_type: null,
        source_type: "class",
        is_prepared: false,
        always_prepared: false,
      },
    ],
    ...patch,
  });
}
