-- Migration: 000031 — seed 016_dnd_2024_background_equipment
BEGIN;

-- Generated by tools/background_equipment_generator.py
-- Source: /home/lucaslima/Projetos/container-lucas/sql/backup/backgrounds.json

CREATE TEMP TABLE _import_background_equipment_option_data (
    background_name TEXT NOT NULL,
    option_key TEXT NOT NULL,
    label TEXT,
    gp_amount NUMERIC(10,2),
    notes TEXT,
    PRIMARY KEY (background_name, option_key)
) ON COMMIT DROP;

INSERT INTO _import_background_equipment_option_data (
    background_name, option_key, label, gp_amount, notes
) VALUES
    ('Acolyte', 'A', 'Option A', 8.00, NULL),
    ('Acolyte', 'B', 'Option B', 50.00, '50 GP'),
    ('Artisan', 'A', 'Option A', 32.00, NULL),
    ('Artisan', 'B', 'Option B', 50.00, '50 GP'),
    ('Charlatan', 'A', 'Option A', 15.00, NULL),
    ('Charlatan', 'B', 'Option B', 50.00, '50 GP'),
    ('Criminal', 'A', 'Option A', 16.00, NULL),
    ('Criminal', 'B', 'Option B', 50.00, '50 GP'),
    ('Entertainer', 'A', 'Option A', 11.00, NULL),
    ('Entertainer', 'B', 'Option B', 50.00, '50 GP'),
    ('Farmer', 'A', 'Option A', 30.00, NULL),
    ('Farmer', 'B', 'Option B', 50.00, '50 GP'),
    ('Guard', 'A', 'Option A', 12.00, NULL),
    ('Guard', 'B', 'Option B', 50.00, '50 GP'),
    ('Guide', 'A', 'Option A', 3.00, NULL),
    ('Guide', 'B', 'Option B', 50.00, '50 GP'),
    ('Hermit', 'A', 'Option A', 16.00, NULL),
    ('Hermit', 'B', 'Option B', 50.00, '50 GP'),
    ('Merchant', 'A', 'Option A', 22.00, NULL),
    ('Merchant', 'B', 'Option B', 50.00, '50 GP'),
    ('Noble', 'A', 'Option A', 29.00, NULL),
    ('Noble', 'B', 'Option B', 50.00, '50 GP'),
    ('Sage', 'A', 'Option A', 8.00, NULL),
    ('Sage', 'B', 'Option B', 50.00, '50 GP'),
    ('Sailor', 'A', 'Option A', 20.00, NULL),
    ('Sailor', 'B', 'Option B', 50.00, '50 GP'),
    ('Scribe', 'A', 'Option A', 23.00, NULL),
    ('Scribe', 'B', 'Option B', 50.00, '50 GP'),
    ('Soldier', 'A', 'Option A', 14.00, NULL),
    ('Soldier', 'B', 'Option B', 50.00, '50 GP'),
    ('Wayfarer', 'A', 'Option A', 16.00, NULL),
    ('Wayfarer', 'B', 'Option B', 50.00, '50 GP');

INSERT INTO background_equipment_options (background_id, option_key, label, gp_amount, notes)
SELECT b.id, data.option_key, data.label, data.gp_amount, data.notes
FROM _import_background_equipment_option_data data
JOIN backgrounds b ON b.name = data.background_name
ON CONFLICT (background_id, option_key) DO UPDATE SET
    label = EXCLUDED.label,
    gp_amount = EXCLUDED.gp_amount,
    notes = EXCLUDED.notes;

CREATE TEMP TABLE _import_background_equipment_item_data (
    background_name TEXT NOT NULL,
    option_key TEXT NOT NULL,
    item_name TEXT NOT NULL,
    quantity INT NOT NULL,
    lookup_name TEXT,
    notes TEXT,
    PRIMARY KEY (background_name, option_key, item_name, quantity)
) ON COMMIT DROP;

INSERT INTO _import_background_equipment_item_data (
    background_name, option_key, item_name, quantity, lookup_name, notes
) VALUES
    ('Acolyte', 'A', 'Calligrapher''s Supplies', 1, 'Calligrapher''s Supplies', NULL),
    ('Acolyte', 'A', 'Book', 1, 'Book', 'prayers'),
    ('Acolyte', 'A', 'Holy Symbol', 1, 'Holy Symbol', NULL),
    ('Acolyte', 'A', 'Parchment', 10, 'Parchment', '10 sheets'),
    ('Acolyte', 'A', 'Robe', 1, 'Robe', NULL),
    ('Artisan', 'A', 'Artisan''s Tools', 1, 'Artisan''s Tools', 'same as above'),
    ('Artisan', 'A', 'Pouches', 2, 'Pouch', NULL),
    ('Artisan', 'A', 'Traveler''s Clothes', 1, 'Traveler''s Clothes', NULL),
    ('Charlatan', 'A', 'Forgery Kit', 1, 'Forgery Kit', NULL),
    ('Charlatan', 'A', 'Costume', 1, 'Costume', NULL),
    ('Charlatan', 'A', 'Fine Clothes', 1, 'Fine Clothes', NULL),
    ('Criminal', 'A', 'Daggers', 2, 'Dagger', NULL),
    ('Criminal', 'A', 'Thieves'' Tools', 1, 'Thieves'' Tools', NULL),
    ('Criminal', 'A', 'Crowbar', 1, 'Crowbar', NULL),
    ('Criminal', 'A', 'Pouches', 2, 'Pouch', NULL),
    ('Criminal', 'A', 'Traveler''s Clothes', 1, 'Traveler''s Clothes', NULL),
    ('Entertainer', 'A', 'Musical Instrument', 1, 'Musical Instrument', 'same as above'),
    ('Entertainer', 'A', 'Costumes', 2, 'Costume', NULL),
    ('Entertainer', 'A', 'Mirror', 1, 'Mirror', NULL),
    ('Entertainer', 'A', 'Perfume', 1, 'Perfume', NULL),
    ('Entertainer', 'A', 'Traveler''s Clothes', 1, 'Traveler''s Clothes', NULL),
    ('Farmer', 'A', 'Sickle', 1, 'Sickle', NULL),
    ('Farmer', 'A', 'Carpenter''s Tools', 1, 'Carpenter''s Tools', NULL),
    ('Farmer', 'A', 'Healer''s Kit', 1, 'Healer''s Kit', NULL),
    ('Farmer', 'A', 'Iron Pot', 1, 'Iron Pot', NULL),
    ('Farmer', 'A', 'Shovel', 1, 'Shovel', NULL),
    ('Guard', 'A', 'Spear', 1, 'Spear', NULL),
    ('Guard', 'A', 'Light Crossbow', 1, 'Light Crossbow', NULL),
    ('Guard', 'A', 'Bolts', 20, 'Bolts (20)', NULL),
    ('Guard', 'A', 'Gaming Set', 1, 'Gaming Set', 'same as above'),
    ('Guard', 'A', 'Hooded Lantern', 1, 'Hooded Lantern', NULL),
    ('Guard', 'A', 'Manacles', 1, 'Manacles', NULL),
    ('Guard', 'A', 'Quiver', 1, 'Quiver', NULL),
    ('Guard', 'A', 'Traveler''s Clothes', 1, 'Traveler''s Clothes', NULL),
    ('Guide', 'A', 'Shortbow', 1, 'Shortbow', NULL),
    ('Guide', 'A', 'Arrows', 20, 'Arrows (20)', NULL),
    ('Guide', 'A', 'Cartographer''s Tools', 1, 'Cartographer''s Tools', NULL),
    ('Guide', 'A', 'Bedroll', 1, 'Bedroll', NULL),
    ('Guide', 'A', 'Quiver', 1, 'Quiver', NULL),
    ('Guide', 'A', 'Tent', 1, 'Tent', NULL),
    ('Guide', 'A', 'Traveler''s Clothes', 1, 'Traveler''s Clothes', NULL),
    ('Hermit', 'A', 'Quarterstaff', 1, 'Quarterstaff', NULL),
    ('Hermit', 'A', 'Herbalism Kit', 1, 'Herbalism Kit', NULL),
    ('Hermit', 'A', 'Bedroll', 1, 'Bedroll', NULL),
    ('Hermit', 'A', 'Book', 1, 'Book', 'philosophy'),
    ('Hermit', 'A', 'Lamp', 1, 'Lamp', NULL),
    ('Hermit', 'A', 'Oil', 3, 'Oil', '3 flasks'),
    ('Hermit', 'A', 'Traveler''s Clothes', 1, 'Traveler''s Clothes', NULL),
    ('Merchant', 'A', 'Navigator''s Tools', 1, 'Navigator''s Tools', NULL),
    ('Merchant', 'A', 'Pouches', 2, 'Pouch', NULL),
    ('Merchant', 'A', 'Traveler''s Clothes', 1, 'Traveler''s Clothes', NULL),
    ('Noble', 'A', 'Gaming Set', 1, 'Gaming Set', 'same as above'),
    ('Noble', 'A', 'Fine Clothes', 1, 'Fine Clothes', NULL),
    ('Noble', 'A', 'Perfume', 1, 'Perfume', NULL),
    ('Sage', 'A', 'Quarterstaff', 1, 'Quarterstaff', NULL),
    ('Sage', 'A', 'Calligrapher''s Supplies', 1, 'Calligrapher''s Supplies', NULL),
    ('Sage', 'A', 'Book', 1, 'Book', 'history'),
    ('Sage', 'A', 'Parchment', 8, 'Parchment', '8 sheets'),
    ('Sage', 'A', 'Robe', 1, 'Robe', NULL),
    ('Sailor', 'A', 'Dagger', 1, 'Dagger', NULL),
    ('Sailor', 'A', 'Navigator''s Tools', 1, 'Navigator''s Tools', NULL),
    ('Sailor', 'A', 'Rope', 1, 'Rope', NULL),
    ('Sailor', 'A', 'Traveler''s Clothes', 1, 'Traveler''s Clothes', NULL),
    ('Scribe', 'A', 'Calligrapher''s Supplies', 1, 'Calligrapher''s Supplies', NULL),
    ('Scribe', 'A', 'Fine Clothes', 1, 'Fine Clothes', NULL),
    ('Scribe', 'A', 'Lamp', 1, 'Lamp', NULL),
    ('Scribe', 'A', 'Oil', 3, 'Oil', '3 flasks'),
    ('Scribe', 'A', 'Parchment', 12, 'Parchment', '12 sheets'),
    ('Soldier', 'A', 'Spear', 1, 'Spear', NULL),
    ('Soldier', 'A', 'Shortbow', 1, 'Shortbow', NULL),
    ('Soldier', 'A', 'Arrows', 20, 'Arrows (20)', NULL),
    ('Soldier', 'A', 'Gaming Set', 1, 'Gaming Set', 'same as above'),
    ('Soldier', 'A', 'Healer''s Kit', 1, 'Healer''s Kit', NULL),
    ('Soldier', 'A', 'Quiver', 1, 'Quiver', NULL),
    ('Soldier', 'A', 'Traveler''s Clothes', 1, 'Traveler''s Clothes', NULL),
    ('Wayfarer', 'A', 'Daggers', 2, 'Dagger', NULL),
    ('Wayfarer', 'A', 'Thieves'' Tools', 1, 'Thieves'' Tools', NULL),
    ('Wayfarer', 'A', 'Gaming Set', 1, 'Gaming Set', 'any'),
    ('Wayfarer', 'A', 'Bedroll', 1, 'Bedroll', NULL),
    ('Wayfarer', 'A', 'Pouches', 2, 'Pouch', NULL),
    ('Wayfarer', 'A', 'Traveler''s Clothes', 1, 'Traveler''s Clothes', NULL);

DELETE FROM background_equipment_items bei
USING background_equipment_options beo, backgrounds b, _import_background_equipment_option_data data
WHERE bei.equipment_option_id = beo.id
  AND beo.background_id = b.id
  AND b.name = data.background_name;

INSERT INTO background_equipment_items (
    equipment_option_id, item_id, item_name, quantity, notes
)
SELECT
    beo.id,
    i.id,
    data.item_name,
    data.quantity,
    data.notes
FROM _import_background_equipment_item_data data
JOIN backgrounds b ON b.name = data.background_name
JOIN background_equipment_options beo
    ON beo.background_id = b.id
   AND beo.option_key = data.option_key
LEFT JOIN items i ON i.name = data.lookup_name;

COMMIT;
