-- Migration: 000005 — efeitos, danos e armas
-- ==========================================
-- 7. EFEITOS, DANOS E RECURSOS
-- ==========================================

CREATE TABLE effects (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trait_id INT REFERENCES traits(id) ON DELETE CASCADE,
    spell_id INT REFERENCES spells(id) ON DELETE CASCADE,
    trait_option_id INT REFERENCES trait_options(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    effect_type VARCHAR(30) NOT NULL DEFAULT 'modifier' CHECK (
        effect_type IN (
            'modifier',
            'damage',
            'healing',
            'status',
            'resource',
            'proficiency',
            'damage_adjustment',
            'condition_adjustment',
            'special'
        )
    ),
    duration_text VARCHAR(100),
    requires_choice BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (
        (trait_id IS NULL OR spell_id IS NULL)
        AND (trait_id IS NULL OR trait_option_id IS NULL)
        AND (spell_id IS NULL OR trait_option_id IS NULL)
    )
);

CREATE TABLE effect_modifiers (
    effect_id INT REFERENCES effects(id) ON DELETE CASCADE,
    affected_stat VARCHAR(50) NOT NULL,
    operation VARCHAR(20) NOT NULL DEFAULT 'add' CHECK (
        operation IN ('add', 'set', 'advantage', 'disadvantage')
    ),
    modifier_value INT,
    CHECK (
        operation IN ('advantage', 'disadvantage')
        OR modifier_value IS NOT NULL
    ),
    PRIMARY KEY (effect_id, affected_stat, operation)
);

CREATE TABLE effect_damage (
    effect_id INT PRIMARY KEY REFERENCES effects(id) ON DELETE CASCADE,
    die_id INT REFERENCES dice(id) ON DELETE RESTRICT,
    damage_type_id INT REFERENCES damage_types(id) ON DELETE RESTRICT,
    die_count INT NOT NULL CHECK (die_count > 0),
    flat_bonus INT NOT NULL DEFAULT 0
);

CREATE TABLE effect_damage_adjustments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    effect_id INT NOT NULL REFERENCES effects(id) ON DELETE CASCADE,
    damage_type_id INT NOT NULL REFERENCES damage_types(id) ON DELETE RESTRICT,
    adjustment_type VARCHAR(20) NOT NULL CHECK (
        adjustment_type IN ('resistance', 'immunity', 'vulnerability')
    ),
    scope_text VARCHAR(255)
);

CREATE TABLE effect_statuses (
    effect_id INT REFERENCES effects(id) ON DELETE CASCADE,
    status_id INT REFERENCES statuses(id) ON DELETE RESTRICT,
    duration_text VARCHAR(100),
    scope_text VARCHAR(255),
    PRIMARY KEY (effect_id, status_id)
);

CREATE TABLE effect_condition_adjustments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    effect_id INT NOT NULL REFERENCES effects(id) ON DELETE CASCADE,
    status_id INT NOT NULL REFERENCES statuses(id) ON DELETE RESTRICT,
    adjustment_type VARCHAR(20) NOT NULL CHECK (
        adjustment_type IN ('advantage', 'disadvantage', 'immunity')
    ),
    scope_text VARCHAR(255)
);

CREATE TABLE effect_proficiencies (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    effect_id INT NOT NULL REFERENCES effects(id) ON DELETE CASCADE,
    proficiency_type VARCHAR(20) NOT NULL CHECK (
        proficiency_type IN ('save', 'skill', 'tool', 'language', 'weapon', 'armor', 'other')
    ),
    language_id INT REFERENCES languages(id) ON DELETE RESTRICT,
    skill_id INT REFERENCES skills(id) ON DELETE RESTRICT,
    tool_id INT REFERENCES tools(id) ON DELETE RESTRICT,
    name VARCHAR(100),
    requires_choice BOOLEAN NOT NULL DEFAULT FALSE,
    choice_count INT NOT NULL DEFAULT 1 CHECK (choice_count > 0),
    notes TEXT,
    CHECK (
        proficiency_type = 'language'
        OR language_id IS NULL
    ),
    CHECK (
        proficiency_type = 'skill'
        OR skill_id IS NULL
    ),
    CHECK (
        proficiency_type = 'tool'
        OR tool_id IS NULL
    ),
    CHECK (
        requires_choice
        OR language_id IS NOT NULL
        OR skill_id IS NOT NULL
        OR tool_id IS NOT NULL
        OR name IS NOT NULL
    )
);

CREATE TABLE character_effects (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id INT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    effect_id INT NOT NULL REFERENCES effects(id) ON DELETE RESTRICT,
    source_type VARCHAR(30),
    source_id INT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    timing_text VARCHAR(100),
    notes TEXT
);

CREATE TABLE character_conditions (
    character_id INT REFERENCES characters(id) ON DELETE CASCADE,
    status_id INT REFERENCES statuses(id) ON DELETE RESTRICT,
    source_effect_id INT REFERENCES effects(id) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    timing_text VARCHAR(100),
    notes TEXT,
    PRIMARY KEY (character_id, status_id)
);

-- ==========================================
-- 8. ARMAS E MAESTRIAS
-- ==========================================

CREATE TABLE weapon_masteries (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    effect_id INT REFERENCES effects(id) ON DELETE SET NULL
);

CREATE TABLE weapon_properties (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE weapons (
    item_id INT PRIMARY KEY REFERENCES items(id) ON DELETE CASCADE,
    damage_effect_id INT REFERENCES effect_damage(effect_id) ON DELETE SET NULL,
    mastery_id INT REFERENCES weapon_masteries(id) ON DELETE SET NULL,
    weapon_category VARCHAR(20) NOT NULL CHECK (
        weapon_category IN ('Simple Melee', 'Simple Ranged', 'Martial Melee', 'Martial Ranged')
    ),
    range_normal INT CHECK (range_normal IS NULL OR range_normal >= 0),
    range_long INT CHECK (range_long IS NULL OR range_long >= 0),
    is_two_handed BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (
        range_normal IS NULL
        OR range_long IS NULL
        OR range_long >= range_normal
    )
);

CREATE TABLE weapon_has_properties (
    item_id INT REFERENCES weapons(item_id) ON DELETE CASCADE,
    property_id INT REFERENCES weapon_properties(id) ON DELETE CASCADE,
    details VARCHAR(100),
    PRIMARY KEY (item_id, property_id)
);
