-- Skill options from 000030 (applied separately on remote)
BEGIN;

CREATE TEMP TABLE _import_class_skill_option_data (
    class_name TEXT NOT NULL,
    choice_group TEXT NOT NULL,
    skill_name TEXT NOT NULL,
    sort_order INT NOT NULL,
    PRIMARY KEY (class_name, choice_group, skill_name)
) ON COMMIT DROP;

INSERT INTO _import_class_skill_option_data (class_name, choice_group, skill_name, sort_order) VALUES
    ('Barbarian', 'Class Skills', 'Animal Handling', 10),
    ('Barbarian', 'Class Skills', 'Athletics', 20),
    ('Barbarian', 'Class Skills', 'Intimidation', 30),
    ('Barbarian', 'Class Skills', 'Nature', 40),
    ('Barbarian', 'Class Skills', 'Perception', 50),
    ('Barbarian', 'Class Skills', 'Survival', 60),
    ('Bard', 'Class Skills', 'Acrobatics', 10),
    ('Bard', 'Class Skills', 'Animal Handling', 20),
    ('Bard', 'Class Skills', 'Arcana', 30),
    ('Bard', 'Class Skills', 'Athletics', 40),
    ('Bard', 'Class Skills', 'Deception', 50),
    ('Bard', 'Class Skills', 'History', 60),
    ('Bard', 'Class Skills', 'Insight', 70),
    ('Bard', 'Class Skills', 'Intimidation', 80),
    ('Bard', 'Class Skills', 'Investigation', 90),
    ('Bard', 'Class Skills', 'Medicine', 100),
    ('Bard', 'Class Skills', 'Nature', 110),
    ('Bard', 'Class Skills', 'Perception', 120),
    ('Bard', 'Class Skills', 'Performance', 130),
    ('Bard', 'Class Skills', 'Persuasion', 140),
    ('Bard', 'Class Skills', 'Religion', 150),
    ('Bard', 'Class Skills', 'Sleight of Hand', 160),
    ('Bard', 'Class Skills', 'Stealth', 170),
    ('Bard', 'Class Skills', 'Survival', 180),
    ('Cleric', 'Class Skills', 'History', 10),
    ('Cleric', 'Class Skills', 'Insight', 20),
    ('Cleric', 'Class Skills', 'Medicine', 30),
    ('Cleric', 'Class Skills', 'Persuasion', 40),
    ('Cleric', 'Class Skills', 'Religion', 50),
    ('Druid', 'Class Skills', 'Animal Handling', 10),
    ('Druid', 'Class Skills', 'Arcana', 20),
    ('Druid', 'Class Skills', 'Insight', 30),
    ('Druid', 'Class Skills', 'Medicine', 40),
    ('Druid', 'Class Skills', 'Nature', 50),
    ('Druid', 'Class Skills', 'Perception', 60),
    ('Druid', 'Class Skills', 'Religion', 70),
    ('Druid', 'Class Skills', 'Survival', 80),
    ('Fighter', 'Class Skills', 'Acrobatics', 10),
    ('Fighter', 'Class Skills', 'Animal Handling', 20),
    ('Fighter', 'Class Skills', 'Athletics', 30),
    ('Fighter', 'Class Skills', 'History', 40),
    ('Fighter', 'Class Skills', 'Insight', 50),
    ('Fighter', 'Class Skills', 'Intimidation', 60),
    ('Fighter', 'Class Skills', 'Persuasion', 70),
    ('Fighter', 'Class Skills', 'Perception', 80),
    ('Fighter', 'Class Skills', 'Survival', 90),
    ('Monk', 'Class Skills', 'Acrobatics', 10),
    ('Monk', 'Class Skills', 'Athletics', 20),
    ('Monk', 'Class Skills', 'History', 30),
    ('Monk', 'Class Skills', 'Insight', 40),
    ('Monk', 'Class Skills', 'Religion', 50),
    ('Monk', 'Class Skills', 'Stealth', 60),
    ('Paladin', 'Class Skills', 'Athletics', 10),
    ('Paladin', 'Class Skills', 'Insight', 20),
    ('Paladin', 'Class Skills', 'Intimidation', 30),
    ('Paladin', 'Class Skills', 'Medicine', 40),
    ('Paladin', 'Class Skills', 'Persuasion', 50),
    ('Paladin', 'Class Skills', 'Religion', 60),
    ('Ranger', 'Class Skills', 'Animal Handling', 10),
    ('Ranger', 'Class Skills', 'Athletics', 20),
    ('Ranger', 'Class Skills', 'Insight', 30),
    ('Ranger', 'Class Skills', 'Investigation', 40),
    ('Ranger', 'Class Skills', 'Nature', 50),
    ('Ranger', 'Class Skills', 'Perception', 60),
    ('Ranger', 'Class Skills', 'Stealth', 70),
    ('Ranger', 'Class Skills', 'Survival', 80),
    ('Rogue', 'Class Skills', 'Acrobatics', 10),
    ('Rogue', 'Class Skills', 'Athletics', 20),
    ('Rogue', 'Class Skills', 'Deception', 30),
    ('Rogue', 'Class Skills', 'Insight', 40),
    ('Rogue', 'Class Skills', 'Intimidation', 50),
    ('Rogue', 'Class Skills', 'Investigation', 60),
    ('Rogue', 'Class Skills', 'Perception', 70),
    ('Rogue', 'Class Skills', 'Persuasion', 80),
    ('Rogue', 'Class Skills', 'Sleight of Hand', 90),
    ('Rogue', 'Class Skills', 'Stealth', 100),
    ('Sorcerer', 'Class Skills', 'Arcana', 10),
    ('Sorcerer', 'Class Skills', 'Deception', 20),
    ('Sorcerer', 'Class Skills', 'Insight', 30),
    ('Sorcerer', 'Class Skills', 'Intimidation', 40),
    ('Sorcerer', 'Class Skills', 'Persuasion', 50),
    ('Sorcerer', 'Class Skills', 'Religion', 60),
    ('Warlock', 'Class Skills', 'Arcana', 10),
    ('Warlock', 'Class Skills', 'Deception', 20),
    ('Warlock', 'Class Skills', 'History', 30),
    ('Warlock', 'Class Skills', 'Intimidation', 40),
    ('Warlock', 'Class Skills', 'Investigation', 50),
    ('Warlock', 'Class Skills', 'Nature', 60),
    ('Warlock', 'Class Skills', 'Religion', 70),
    ('Wizard', 'Class Skills', 'Arcana', 10),
    ('Wizard', 'Class Skills', 'History', 20),
    ('Wizard', 'Class Skills', 'Insight', 30),
    ('Wizard', 'Class Skills', 'Investigation', 40),
    ('Wizard', 'Class Skills', 'Medicine', 50),
    ('Wizard', 'Class Skills', 'Religion', 60);

INSERT INTO class_skill_options (class_id, choice_group, skill_id, sort_order)
SELECT c.id, data.choice_group, s.id, data.sort_order
FROM _import_class_skill_option_data data
JOIN classes c ON c.name = data.class_name
JOIN skills s ON s.name = data.skill_name
ON CONFLICT (class_id, choice_group, skill_id) DO UPDATE SET
    sort_order = EXCLUDED.sort_order;

COMMIT;
