-- Migration: 000003 — players, campaigns, characters
-- ==========================================
-- 3. JOGADORES E CAMPANHAS
-- ==========================================

CREATE TABLE players (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    avatar_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE campaigns (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ==========================================
-- 4. PERSONAGENS (TABELA CENTRAL)
-- ==========================================

CREATE TABLE characters (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_player_id UUID NOT NULL DEFAULT (auth.uid()) REFERENCES players(id) ON DELETE CASCADE,
    species_id INT REFERENCES species(id) ON DELETE SET NULL,
    background_id INT REFERENCES backgrounds(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    level INT NOT NULL DEFAULT 1 CHECK (level BETWEEN 1 AND 20),
    size VARCHAR(20) NOT NULL DEFAULT 'Medium' CHECK (
        size IN ('Tiny', 'Small', 'Medium', 'Large', 'Huge', 'Gargantuan')
    ),
    speed INT NOT NULL DEFAULT 30 CHECK (speed >= 0),
    max_hp INT NOT NULL DEFAULT 1 CHECK (max_hp > 0),
    current_hp INT NOT NULL DEFAULT 1 CHECK (current_hp >= 0),
    temporary_hp INT NOT NULL DEFAULT 0 CHECK (temporary_hp >= 0),
    death_save_successes INT NOT NULL DEFAULT 0 CHECK (death_save_successes BETWEEN 0 AND 3),
    death_save_failures INT NOT NULL DEFAULT 0 CHECK (death_save_failures BETWEEN 0 AND 3),
    heroic_inspiration BOOLEAN NOT NULL DEFAULT FALSE,
    strength INT NOT NULL DEFAULT 10 CHECK (strength BETWEEN 1 AND 30),
    dexterity INT NOT NULL DEFAULT 10 CHECK (dexterity BETWEEN 1 AND 30),
    constitution INT NOT NULL DEFAULT 10 CHECK (constitution BETWEEN 1 AND 30),
    intelligence INT NOT NULL DEFAULT 10 CHECK (intelligence BETWEEN 1 AND 30),
    wisdom INT NOT NULL DEFAULT 10 CHECK (wisdom BETWEEN 1 AND 30),
    charisma INT NOT NULL DEFAULT 10 CHECK (charisma BETWEEN 1 AND 30),
    proficiency_bonus INT NOT NULL DEFAULT 2 CHECK (proficiency_bonus BETWEEN 2 AND 6),
    armor_class INT NOT NULL DEFAULT 10 CHECK (armor_class > 0),
    experience_points INT NOT NULL DEFAULT 0 CHECK (experience_points >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (current_hp <= max_hp)
);
