-- Ouro inicial por nível (PHB 2024) + unlock_level em subclasses.

BEGIN;

ALTER TABLE subclasses
    ADD COLUMN IF NOT EXISTS unlock_level INT NOT NULL DEFAULT 3
    CHECK (unlock_level BETWEEN 1 AND 20);

COMMENT ON COLUMN subclasses.unlock_level IS
    'Nível mínimo de classe para escolher esta subclasse (SRD 2024: 3).';

CREATE TABLE IF NOT EXISTS starting_gold_tiers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_level INT NOT NULL CHECK (min_level BETWEEN 1 AND 20),
    max_level INT NOT NULL CHECK (max_level BETWEEN 1 AND 20),
    base_gp INT NOT NULL DEFAULT 0 CHECK (base_gp >= 0),
    bonus_dice_count INT NOT NULL DEFAULT 0 CHECK (bonus_dice_count >= 0),
    bonus_dice_sides INT NOT NULL DEFAULT 0 CHECK (bonus_dice_sides >= 0),
    bonus_dice_multiplier INT NOT NULL DEFAULT 0 CHECK (bonus_dice_multiplier >= 0),
    notes TEXT,
    CHECK (max_level >= min_level),
    UNIQUE (min_level, max_level)
);

INSERT INTO starting_gold_tiers (
    min_level, max_level, base_gp, bonus_dice_count, bonus_dice_sides, bonus_dice_multiplier, notes
) VALUES
    (1, 1, 0, 0, 0, 0, 'Equipamento normal do antecedente (nível 1).'),
    (2, 4, 0, 0, 0, 0, 'PHB 2024: equipamento normal; itens mágicos comuns fora do escopo v1.'),
    (5, 10, 500, 1, 10, 25, 'PHB 2024: 500 GP + 1d10 × 25 GP + equipamento normal.'),
    (11, 16, 5000, 1, 10, 250, 'PHB 2024: 5.000 GP + 1d10 × 250 GP + equipamento normal.'),
    (17, 20, 20000, 1, 10, 250, 'PHB 2024: 20.000 GP + 1d10 × 250 GP + equipamento normal.')
ON CONFLICT (min_level, max_level) DO UPDATE SET
    base_gp = EXCLUDED.base_gp,
    bonus_dice_count = EXCLUDED.bonus_dice_count,
    bonus_dice_sides = EXCLUDED.bonus_dice_sides,
    bonus_dice_multiplier = EXCLUDED.bonus_dice_multiplier,
    notes = EXCLUDED.notes;

ALTER TABLE starting_gold_tiers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read starting gold tiers"
    ON starting_gold_tiers FOR SELECT TO authenticated USING (true);

GRANT SELECT ON starting_gold_tiers TO authenticated, service_role;

COMMIT;
