-- Migration: 000002 — tabelas de catálogo (vazias até seeds)
-- ==========================================
-- 2. CONTEUDO BASE DO JOGO
-- ==========================================

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    creature_type VARCHAR(50) NOT NULL DEFAULT 'Humanoid',
    size_options VARCHAR(50) NOT NULL DEFAULT 'Medium',
    base_speed INT NOT NULL DEFAULT 30 CHECK (base_speed >= 0)
);

CREATE TABLE feats (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(30) NOT NULL DEFAULT 'General' CHECK (
        category IN ('Origin', 'General', 'Fighting Style', 'Epic Boon', 'Other')
    ),
    prerequisite_text TEXT,
    is_repeatable BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT
);

CREATE TABLE backgrounds (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_feat_id INT REFERENCES feats(id) ON DELETE SET NULL,
    origin_feat_selection_key VARCHAR(100),
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE traits (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    activation_scope VARCHAR(20) NOT NULL DEFAULT 'equipped'
        CHECK (activation_scope IN ('equipped', 'carried'))
);

CREATE TABLE spell_lists (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    source_type VARCHAR(30) NOT NULL DEFAULT 'class' CHECK (
        source_type IN ('class', 'species', 'feat', 'other')
    ),
    description TEXT
);

CREATE TABLE trait_option_groups (
    trait_id INT NOT NULL REFERENCES traits(id) ON DELETE CASCADE,
    option_group VARCHAR(100) NOT NULL,
    choice_count INT NOT NULL DEFAULT 1 CHECK (choice_count > 0),
    is_required BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT,
    PRIMARY KEY (trait_id, option_group)
);

CREATE TABLE trait_options (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trait_id INT NOT NULL REFERENCES traits(id) ON DELETE CASCADE,
    option_group VARCHAR(100) NOT NULL DEFAULT 'default',
    skill_id INT REFERENCES skills(id) ON DELETE RESTRICT,
    tool_id INT REFERENCES tools(id) ON DELETE RESTRICT,
    spell_list_id INT REFERENCES spell_lists(id) ON DELETE RESTRICT,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    FOREIGN KEY (trait_id, option_group)
        REFERENCES trait_option_groups(trait_id, option_group)
        ON DELETE CASCADE,
    CHECK (
        (skill_id IS NOT NULL)::INT
        + (tool_id IS NOT NULL)::INT
        + (spell_list_id IS NOT NULL)::INT <= 1
    ),
    UNIQUE (trait_id, option_group, name),
    UNIQUE (id, trait_id),
    UNIQUE (id, trait_id, option_group),
    UNIQUE (id, spell_list_id)
);

CREATE TABLE spells (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    level INT NOT NULL CHECK (level BETWEEN 0 AND 9),
    school VARCHAR(50),
    casting_time VARCHAR(200),
    range_text VARCHAR(100),
    components VARCHAR(20),
    material_component TEXT,
    duration_text VARCHAR(100),
    save_attribute VARCHAR(3) CHECK (
        save_attribute IS NULL
        OR save_attribute IN ('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA')
    ),
    attack_type VARCHAR(20) CHECK (
        attack_type IS NULL
        OR attack_type IN ('Melee Spell', 'Ranged Spell', 'Melee Weapon', 'Ranged Weapon')
    ),
    can_affect_character BOOLEAN NOT NULL DEFAULT FALSE,
    character_effect_scope VARCHAR(30) CHECK (
        character_effect_scope IS NULL
        OR character_effect_scope IN ('Self', 'Touch', 'Creature', 'Party', 'Area', 'Object', 'Special')
    ),
    character_effect_category VARCHAR(30) CHECK (
        character_effect_category IS NULL
        OR character_effect_category IN (
            'Healing',
            'Defense',
            'Buff',
            'Mobility',
            'Sense',
            'Communication',
            'Utility',
            'Summoning',
            'Condition Removal',
            'Resource',
            'Special'
        )
    ),
    character_effect_summary TEXT,
    requires_concentration BOOLEAN NOT NULL DEFAULT FALSE,
    requires_ritual BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,
    UNIQUE (id, level)
);

CREATE TABLE spell_list_spells (
    spell_list_id INT REFERENCES spell_lists(id) ON DELETE CASCADE,
    spell_id INT REFERENCES spells(id) ON DELETE CASCADE,
    PRIMARY KEY (spell_list_id, spell_id)
);

CREATE TABLE spell_rolls (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spell_id INT NOT NULL REFERENCES spells(id) ON DELETE CASCADE,
    roll_label VARCHAR(120) NOT NULL,
    roll_type VARCHAR(30) NOT NULL CHECK (
        roll_type IN (
            'damage',
            'damage_reduction',
            'healing',
            'temporary_hp',
            'hit_points',
            'bonus',
            'penalty',
            'random',
            'utility',
            'summon_attack',
            'special'
        )
    ),
    damage_type_id INT REFERENCES damage_types(id) ON DELETE RESTRICT,
    damage_type_options TEXT,
    formula TEXT NOT NULL,
    base_cast_level INT NOT NULL CHECK (base_cast_level BETWEEN 0 AND 9),
    minimum_cast_level INT NOT NULL CHECK (minimum_cast_level BETWEEN 0 AND 9),
    scaling_type VARCHAR(30) NOT NULL DEFAULT 'none' CHECK (
        scaling_type IN ('none', 'slot', 'cantrip', 'slot_table', 'special')
    ),
    scaling_formula TEXT,
    roll_context VARCHAR(255),
    sort_order INT NOT NULL DEFAULT 0,
    UNIQUE (spell_id, roll_label),
    CHECK (minimum_cast_level >= base_cast_level)
);

CREATE TABLE classes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    hit_die VARCHAR(5) NOT NULL CHECK (hit_die IN ('d6', 'd8', 'd10', 'd12'))
);

CREATE TABLE subclasses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    UNIQUE (class_id, name)
);
