-- Migration: 000004 — inventário, relações e progressão base
-- ==========================================
-- 5. SISTEMA DE INVENTARIO E EQUIPAMENTOS
-- ==========================================

CREATE TABLE items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    cost_gp NUMERIC(10,2) CHECK (cost_gp IS NULL OR cost_gp >= 0),
    weight_lb NUMERIC(8,2) CHECK (weight_lb IS NULL OR weight_lb >= 0),
    is_magical BOOLEAN NOT NULL DEFAULT FALSE,
    requires_attunement BOOLEAN NOT NULL DEFAULT FALSE,
    is_consumable BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE inventory (
    character_id INT REFERENCES characters(id) ON DELETE CASCADE,
    item_id INT REFERENCES items(id) ON DELETE CASCADE,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    is_equipped BOOLEAN NOT NULL DEFAULT FALSE,
    is_attuned BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (character_id, item_id)
);

CREATE TABLE armors (
    item_id INT PRIMARY KEY REFERENCES items(id) ON DELETE CASCADE,
    ac_bonus INT NOT NULL CHECK (ac_bonus >= 0),
    category VARCHAR(20) NOT NULL CHECK (
        category IN ('Light', 'Medium', 'Heavy', 'Shield')
    ),
    min_strength INT NOT NULL DEFAULT 0 CHECK (min_strength >= 0),
    stealth_disadvantage BOOLEAN NOT NULL DEFAULT FALSE,
    plus_dex_modifier BOOLEAN NOT NULL DEFAULT TRUE,
    max_dex_bonus INT CHECK (max_dex_bonus IS NULL OR max_dex_bonus >= 0)
);

-- ==========================================
-- 6. RELACIONAMENTOS E PROGRESSAO
-- ==========================================

CREATE TABLE player_campaigns (
    player_id UUID REFERENCES players(id) ON DELETE CASCADE,
    campaign_id INT REFERENCES campaigns(id) ON DELETE CASCADE,
    role_id INT REFERENCES roles(id) ON DELETE SET NULL,
    PRIMARY KEY (player_id, campaign_id)
);

CREATE TABLE player_characters (
    player_id UUID REFERENCES players(id) ON DELETE CASCADE,
    character_id INT REFERENCES characters(id) ON DELETE CASCADE,
    campaign_id INT REFERENCES campaigns(id) ON DELETE CASCADE,
    PRIMARY KEY (player_id, character_id),
    UNIQUE (character_id, campaign_id)
);

CREATE TABLE character_classes (
    character_id INT REFERENCES characters(id) ON DELETE CASCADE,
    class_id INT REFERENCES classes(id) ON DELETE RESTRICT,
    subclass_id INT REFERENCES subclasses(id) ON DELETE SET NULL,
    class_level INT NOT NULL DEFAULT 1 CHECK (class_level BETWEEN 1 AND 20),
    PRIMARY KEY (character_id, class_id)
);

CREATE TABLE class_traits (
    class_id INT REFERENCES classes(id) ON DELETE CASCADE,
    trait_id INT REFERENCES traits(id) ON DELETE CASCADE,
    level_required INT NOT NULL CHECK (level_required BETWEEN 1 AND 20),
    PRIMARY KEY (class_id, trait_id, level_required)
);

CREATE TABLE subclass_traits (
    subclass_id INT REFERENCES subclasses(id) ON DELETE CASCADE,
    trait_id INT REFERENCES traits(id) ON DELETE CASCADE,
    level_required INT NOT NULL CHECK (level_required BETWEEN 1 AND 20),
    PRIMARY KEY (subclass_id, trait_id, level_required)
);

CREATE TABLE background_ability_options (
    background_id INT REFERENCES backgrounds(id) ON DELETE CASCADE,
    ability VARCHAR(3) NOT NULL CHECK (
        ability IN ('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA')
    ),
    PRIMARY KEY (background_id, ability)
);

CREATE TABLE background_skill_proficiencies (
    background_id INT REFERENCES backgrounds(id) ON DELETE CASCADE,
    skill_id INT REFERENCES skills(id) ON DELETE RESTRICT,
    PRIMARY KEY (background_id, skill_id)
);

CREATE TABLE background_tool_proficiency_options (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    background_id INT NOT NULL REFERENCES backgrounds(id) ON DELETE CASCADE,
    option_group VARCHAR(100) NOT NULL DEFAULT 'Tool Proficiency',
    choice_count INT NOT NULL DEFAULT 1 CHECK (choice_count > 0),
    tool_id INT REFERENCES tools(id) ON DELETE RESTRICT,
    tool_category VARCHAR(30) CHECK (
        tool_category IS NULL
        OR tool_category IN ('Artisan', 'Gaming Set', 'Musical Instrument', 'Other')
    ),
    name VARCHAR(100) NOT NULL,
    notes TEXT,
    CHECK (
        tool_id IS NOT NULL
        OR tool_category IS NOT NULL
        OR name IS NOT NULL
    ),
    UNIQUE (background_id, option_group, name)
);

CREATE TABLE feat_traits (
    feat_id INT REFERENCES feats(id) ON DELETE CASCADE,
    trait_id INT REFERENCES traits(id) ON DELETE CASCADE,
    PRIMARY KEY (feat_id, trait_id)
);

CREATE TABLE species_traits (
    species_id INT REFERENCES species(id) ON DELETE CASCADE,
    trait_id INT REFERENCES traits(id) ON DELETE CASCADE,
    PRIMARY KEY (species_id, trait_id)
);

CREATE TABLE item_traits (
    item_id INT REFERENCES items(id) ON DELETE CASCADE,
    trait_id INT REFERENCES traits(id) ON DELETE CASCADE,
    PRIMARY KEY (item_id, trait_id)
);

CREATE TABLE trait_spells (
    trait_id INT REFERENCES traits(id) ON DELETE CASCADE,
    spell_id INT REFERENCES spells(id) ON DELETE CASCADE,
    charge_cost INT CHECK (charge_cost IS NULL OR charge_cost >= 0),
    notes TEXT,
    PRIMARY KEY (trait_id, spell_id)
);

CREATE TABLE trait_option_spells (
    trait_option_id INT REFERENCES trait_options(id) ON DELETE CASCADE,
    spell_id INT REFERENCES spells(id) ON DELETE CASCADE,
    level_required INT NOT NULL DEFAULT 1 CHECK (level_required BETWEEN 1 AND 20),
    always_prepared BOOLEAN NOT NULL DEFAULT TRUE,
    free_casts_per VARCHAR(20) CHECK (
        free_casts_per IS NULL
        OR free_casts_per IN ('Short Rest', 'Long Rest', 'Other')
    ),
    notes TEXT,
    PRIMARY KEY (trait_option_id, spell_id, level_required)
);

CREATE TABLE trait_spell_choice_groups (
    trait_id INT REFERENCES traits(id) ON DELETE CASCADE,
    choice_group VARCHAR(100) NOT NULL,
    choice_count INT NOT NULL CHECK (choice_count > 0),
    spell_level INT CHECK (spell_level IS NULL OR spell_level BETWEEN 0 AND 9),
    spell_list_option_group VARCHAR(100),
    always_prepared BOOLEAN NOT NULL DEFAULT FALSE,
    free_casts_per VARCHAR(20) CHECK (
        free_casts_per IS NULL
        OR free_casts_per IN ('Short Rest', 'Long Rest', 'Other')
    ),
    notes TEXT,
    PRIMARY KEY (trait_id, choice_group),
    UNIQUE (trait_id, choice_group, spell_level)
);

CREATE TABLE trait_option_modifiers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trait_option_id INT NOT NULL,
    trait_id INT NOT NULL,
    choice_mode_key VARCHAR(100) NOT NULL DEFAULT 'default',
    affected_stat VARCHAR(50) NOT NULL,
    operation VARCHAR(20) NOT NULL DEFAULT 'add' CHECK (
        operation IN ('add', 'set', 'advantage', 'disadvantage')
    ),
    modifier_value INT,
    max_value INT CHECK (max_value IS NULL OR max_value > 0),
    scope_text VARCHAR(255),
    FOREIGN KEY (trait_option_id, trait_id)
        REFERENCES trait_options(id, trait_id)
        ON DELETE CASCADE,
    CHECK (
        operation IN ('advantage', 'disadvantage')
        OR modifier_value IS NOT NULL
    ),
    UNIQUE (
        trait_option_id,
        choice_mode_key,
        affected_stat,
        operation
    )
);

CREATE TABLE character_skills (
    character_id INT REFERENCES characters(id) ON DELETE CASCADE,
    skill_id INT REFERENCES skills(id) ON DELETE RESTRICT,
    is_proficient BOOLEAN NOT NULL DEFAULT FALSE,
    has_expertise BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (character_id, skill_id),
    CHECK (NOT has_expertise OR is_proficient)
);

CREATE TABLE character_proficiencies (
    character_id INT REFERENCES characters(id) ON DELETE CASCADE,
    proficiency_type VARCHAR(20) NOT NULL CHECK (
        proficiency_type IN ('save', 'tool', 'language', 'weapon', 'armor', 'other')
    ),
    tool_id INT REFERENCES tools(id) ON DELETE RESTRICT,
    name VARCHAR(100) NOT NULL,
    source_type VARCHAR(30),
    source_id INT,
    PRIMARY KEY (character_id, proficiency_type, name),
    CHECK (
        proficiency_type = 'tool'
        OR tool_id IS NULL
    )
);

CREATE TABLE character_feats (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id INT REFERENCES characters(id) ON DELETE CASCADE,
    feat_id INT REFERENCES feats(id) ON DELETE RESTRICT,
    source_type VARCHAR(30),
    source_id INT,
    selection_key VARCHAR(100),
    notes TEXT
);

CREATE TABLE character_trait_options (
    character_id INT REFERENCES characters(id) ON DELETE CASCADE,
    trait_id INT NOT NULL,
    option_group VARCHAR(100) NOT NULL DEFAULT 'default',
    selection_key VARCHAR(100) NOT NULL DEFAULT 'default',
    trait_option_id INT NOT NULL,
    source_type VARCHAR(30),
    source_id INT,
    notes TEXT,
    PRIMARY KEY (character_id, trait_id, option_group, selection_key),
    FOREIGN KEY (trait_option_id, trait_id, option_group)
        REFERENCES trait_options(id, trait_id, option_group)
        ON DELETE RESTRICT
);

CREATE TABLE character_trait_spell_choices (
    character_id INT REFERENCES characters(id) ON DELETE CASCADE,
    trait_id INT NOT NULL,
    choice_group VARCHAR(100) NOT NULL,
    selection_key VARCHAR(100) NOT NULL,
    spell_level INT NOT NULL CHECK (spell_level BETWEEN 0 AND 9),
    spell_id INT NOT NULL REFERENCES spells(id) ON DELETE RESTRICT,
    trait_option_id INT,
    spell_list_id INT,
    source_type VARCHAR(30),
    source_id INT,
    notes TEXT,
    PRIMARY KEY (character_id, trait_id, choice_group, selection_key),
    FOREIGN KEY (trait_id, choice_group)
        REFERENCES trait_spell_choice_groups(trait_id, choice_group)
        ON DELETE CASCADE,
    FOREIGN KEY (trait_id, choice_group, spell_level)
        REFERENCES trait_spell_choice_groups(trait_id, choice_group, spell_level)
        ON DELETE CASCADE,
    FOREIGN KEY (spell_id, spell_level)
        REFERENCES spells(id, level)
        ON DELETE RESTRICT,
    FOREIGN KEY (spell_list_id, spell_id)
        REFERENCES spell_list_spells(spell_list_id, spell_id)
        ON DELETE RESTRICT,
    FOREIGN KEY (trait_option_id, spell_list_id)
        REFERENCES trait_options(id, spell_list_id)
        ON DELETE RESTRICT
);

CREATE TABLE character_spells (
    character_id INT REFERENCES characters(id) ON DELETE CASCADE,
    spell_id INT REFERENCES spells(id) ON DELETE RESTRICT,
    source_type VARCHAR(30),
    is_prepared BOOLEAN NOT NULL DEFAULT FALSE,
    always_prepared BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (character_id, spell_id)
);

CREATE TABLE character_spell_slots (
    character_id INT REFERENCES characters(id) ON DELETE CASCADE,
    slot_level INT NOT NULL CHECK (slot_level BETWEEN 1 AND 9),
    max_slots INT NOT NULL CHECK (max_slots >= 0),
    used_slots INT NOT NULL DEFAULT 0 CHECK (used_slots >= 0),
    PRIMARY KEY (character_id, slot_level),
    CHECK (used_slots <= max_slots)
);

CREATE TABLE character_resources (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id INT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    trait_id INT REFERENCES traits(id) ON DELETE CASCADE,
    resource_key VARCHAR(80),
    name VARCHAR(100) NOT NULL,
    max_uses INT NOT NULL CHECK (max_uses >= 0),
    used_uses INT NOT NULL DEFAULT 0 CHECK (used_uses >= 0),
    reset_on VARCHAR(20) CHECK (reset_on IN ('Short Rest', 'Long Rest', 'Dawn', 'Other')),
    source_type VARCHAR(30),
    source_id INT,
    CHECK (used_uses <= max_uses)
);

CREATE UNIQUE INDEX uq_character_resources_trait_key
    ON character_resources(character_id, trait_id, resource_key)
    WHERE trait_id IS NOT NULL AND resource_key IS NOT NULL;

CREATE UNIQUE INDEX uq_character_resources_name_fallback
    ON character_resources(character_id, name)
    WHERE trait_id IS NULL OR resource_key IS NULL;
