-- Migration: 000001 — schema private + tabelas de referência
DROP SCHEMA IF EXISTS private CASCADE;
CREATE SCHEMA private;

-- ==========================================
-- 1. TABELAS DE REFERENCIA (ESTATICAS)
-- ==========================================

CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE dice (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE,
    sides INT NOT NULL UNIQUE CHECK (sides > 0)
);

CREATE TABLE damage_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE languages (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(30) NOT NULL DEFAULT 'Standard' CHECK (
        category IN ('Standard', 'Rare', 'Other')
    ),
    script VARCHAR(100),
    description TEXT
);

CREATE TABLE statuses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE skills (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    base_attribute VARCHAR(3) NOT NULL CHECK (
        base_attribute IN ('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA')
    )
);

CREATE TABLE tools (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(30) NOT NULL CHECK (
        category IN ('Artisan', 'Gaming Set', 'Musical Instrument', 'Other')
    ),
    base_attribute VARCHAR(3) NOT NULL CHECK (
        base_attribute IN ('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA')
    ),
    description TEXT,
    cost_gp NUMERIC(10,2) CHECK (cost_gp IS NULL OR cost_gp >= 0),
    weight_lb NUMERIC(8,2) CHECK (weight_lb IS NULL OR weight_lb >= 0),
    utilize_text TEXT,
    craft_text TEXT
);
