-- Migration: 000007 — progressão, proficiências, recursos
-- ==========================================
-- PROGRESSÃO, PROFICIÊNCIAS, RECURSOS
-- ==========================================

CREATE TABLE spellcasting_progressions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE,
    progression_type VARCHAR(30) NOT NULL CHECK (
        progression_type IN ('full', 'half', 'third', 'pact', 'none')
    ),
    slot_recovery VARCHAR(20) NOT NULL DEFAULT 'Long Rest' CHECK (
        slot_recovery IN ('Short Rest', 'Long Rest', 'Other')
    ),
    description TEXT
);

CREATE TABLE spell_slot_progressions (
    progression_id INT NOT NULL REFERENCES spellcasting_progressions(id) ON DELETE CASCADE,
    class_level INT NOT NULL CHECK (class_level BETWEEN 1 AND 20),
    slot_level INT NOT NULL CHECK (slot_level BETWEEN 1 AND 9),
    slot_count INT NOT NULL CHECK (slot_count >= 0),
    PRIMARY KEY (progression_id, class_level, slot_level)
);

CREATE TABLE spell_knowledge_progressions (
    slug VARCHAR(30) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    knowledge_type VARCHAR(20) NOT NULL CHECK (
        knowledge_type IN ('cantrips', 'prepared', 'known', 'invocations')
    ),
    description TEXT
);

CREATE TABLE spell_knowledge_by_level (
    progression_slug VARCHAR(30) NOT NULL REFERENCES spell_knowledge_progressions(slug) ON DELETE CASCADE,
    class_level INT NOT NULL CHECK (class_level BETWEEN 1 AND 20),
    knowledge_count INT NOT NULL CHECK (knowledge_count >= 0),
    PRIMARY KEY (progression_slug, class_level)
);

CREATE TABLE subclass_spellcasting (
    subclass_id INT PRIMARY KEY REFERENCES subclasses(id) ON DELETE CASCADE,
    progression_slug VARCHAR(30) NOT NULL REFERENCES spellcasting_progressions(slug) ON DELETE RESTRICT,
    spell_list_class VARCHAR(30) NOT NULL,
    cantrip_progression_slug VARCHAR(30) REFERENCES spell_knowledge_progressions(slug) ON DELETE SET NULL,
    prepared_progression_slug VARCHAR(30) REFERENCES spell_knowledge_progressions(slug) ON DELETE SET NULL,
    notes TEXT
);

CREATE TABLE class_spellcasting (
    class_id INT PRIMARY KEY REFERENCES classes(id) ON DELETE CASCADE,
    progression_id INT NOT NULL REFERENCES spellcasting_progressions(id) ON DELETE RESTRICT,
    spellcasting_ability VARCHAR(3) CHECK (
        spellcasting_ability IS NULL
        OR spellcasting_ability IN ('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA')
    ),
    cantrip_progression VARCHAR(30),
    uses_spellbook BOOLEAN NOT NULL DEFAULT FALSE,
    spells_prepared_formula TEXT,
    prepared_progression_slug VARCHAR(30) REFERENCES spell_knowledge_progressions(slug) ON DELETE SET NULL,
    notes TEXT
);

CREATE TABLE class_saving_throws (
    class_id INT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    ability VARCHAR(3) NOT NULL CHECK (
        ability IN ('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA')
    ),
    PRIMARY KEY (class_id, ability)
);

CREATE TABLE class_weapon_proficiencies (
    class_id INT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    notes TEXT,
    PRIMARY KEY (class_id, name)
);

CREATE TABLE class_armor_proficiencies (
    class_id INT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (class_id, name)
);

CREATE TABLE class_tool_proficiency_options (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    option_group VARCHAR(100) NOT NULL DEFAULT 'Tool Proficiency',
    choice_count INT NOT NULL DEFAULT 1 CHECK (choice_count > 0),
    tool_id INT REFERENCES tools(id) ON DELETE RESTRICT,
    tool_category VARCHAR(30) CHECK (
        tool_category IS NULL
        OR tool_category IN ('Artisan', 'Gaming Set', 'Musical Instrument', 'Other')
    ),
    name VARCHAR(100) NOT NULL,
    notes TEXT,
    CHECK (
        tool_id IS NOT NULL
        OR tool_category IS NOT NULL
        OR name IS NOT NULL
    ),
    UNIQUE (class_id, option_group, name)
);

CREATE TABLE class_skill_choice_groups (
    class_id INT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    choice_group VARCHAR(100) NOT NULL DEFAULT 'Class Skills',
    choice_count INT NOT NULL CHECK (choice_count > 0),
    notes TEXT,
    PRIMARY KEY (class_id, choice_group)
);

CREATE TABLE class_skill_options (
    class_id INT NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    choice_group VARCHAR(100) NOT NULL DEFAULT 'Class Skills',
    skill_id INT NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
    sort_order INT NOT NULL DEFAULT 0,
    PRIMARY KEY (class_id, choice_group, skill_id),
    FOREIGN KEY (class_id, choice_group)
        REFERENCES class_skill_choice_groups(class_id, choice_group)
        ON DELETE CASCADE
);

CREATE TABLE background_equipment_options (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    background_id INT NOT NULL REFERENCES backgrounds(id) ON DELETE CASCADE,
    option_key VARCHAR(10) NOT NULL,
    label TEXT,
    gp_amount NUMERIC(10,2) CHECK (gp_amount IS NULL OR gp_amount >= 0),
    notes TEXT,
    UNIQUE (background_id, option_key)
);

CREATE TABLE background_equipment_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_option_id INT NOT NULL REFERENCES background_equipment_options(id) ON DELETE CASCADE,
    item_id INT REFERENCES items(id) ON DELETE SET NULL,
    item_name VARCHAR(100) NOT NULL,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    notes TEXT
);

CREATE INDEX idx_class_tool_options_class ON class_tool_proficiency_options(class_id);
CREATE INDEX idx_class_skill_options_skill ON class_skill_options(skill_id);
CREATE INDEX idx_background_equipment_items_option ON background_equipment_items(equipment_option_id);
CREATE INDEX idx_background_equipment_items_item ON background_equipment_items(item_id);


CREATE TABLE trait_resources (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trait_id INT NOT NULL REFERENCES traits(id) ON DELETE CASCADE,
    resource_key VARCHAR(80) NOT NULL,
    resource_name VARCHAR(100) NOT NULL,
    count_type VARCHAR(30) NOT NULL CHECK (
        count_type IN ('fixed', 'by_level', 'equals_level', 'ability_modifier', 'pool_multiplier')
    ),
    ability VARCHAR(3) CHECK (
        ability IS NULL
        OR ability IN ('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA')
    ),
    minimum_count INT NOT NULL DEFAULT 1 CHECK (minimum_count >= 0),
    pool_multiplier INT CHECK (pool_multiplier IS NULL OR pool_multiplier > 0),
    reset_on VARCHAR(30) CHECK (
        reset_on IS NULL
        OR reset_on IN ('Short Rest', 'Long Rest', 'Short and Long Rest', 'Dawn', 'None')
    ),
    short_rest_recovery VARCHAR(20) CHECK (
        short_rest_recovery IS NULL
        OR short_rest_recovery IN ('all', 'one', 'none')
    ),
    long_rest_recovery VARCHAR(20) CHECK (
        long_rest_recovery IS NULL
        OR long_rest_recovery IN ('all', 'one', 'none')
    ),
    notes TEXT,
    UNIQUE (trait_id, resource_key)
);

CREATE TABLE trait_resource_progressions (
    trait_resource_id INT NOT NULL REFERENCES trait_resources(id) ON DELETE CASCADE,
    class_level INT NOT NULL CHECK (class_level BETWEEN 1 AND 20),
    resource_count INT CHECK (resource_count IS NULL OR resource_count >= 0),
    die_value VARCHAR(10),
    bonus_value INT,
    PRIMARY KEY (trait_resource_id, class_level)
);

CREATE TABLE trait_resource_dice (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trait_id INT NOT NULL REFERENCES traits(id) ON DELETE CASCADE,
    die_key VARCHAR(50) NOT NULL,
    die_name VARCHAR(100) NOT NULL,
    die_kind VARCHAR(20) NOT NULL DEFAULT 'die' CHECK (die_kind IN ('die', 'bonus')),
    UNIQUE (trait_id, die_key)
);

CREATE TABLE trait_resource_die_progressions (
    trait_resource_die_id INT NOT NULL REFERENCES trait_resource_dice(id) ON DELETE CASCADE,
    class_level INT NOT NULL CHECK (class_level BETWEEN 1 AND 20),
    die_value VARCHAR(10) NOT NULL,
    PRIMARY KEY (trait_resource_die_id, class_level)
);

CREATE INDEX idx_spell_slot_progressions_level ON spell_slot_progressions(class_level, slot_level);
CREATE INDEX idx_class_spellcasting_progression ON class_spellcasting(progression_id);
CREATE INDEX idx_class_spellcasting_prepared_progression ON class_spellcasting(prepared_progression_slug);
CREATE INDEX idx_trait_resources_trait ON trait_resources(trait_id);
CREATE INDEX idx_trait_resource_progressions_level ON trait_resource_progressions(class_level);
CREATE INDEX idx_trait_resource_dice_trait ON trait_resource_dice(trait_id);
CREATE INDEX idx_spell_knowledge_by_level_level ON spell_knowledge_by_level(class_level);
CREATE INDEX idx_subclass_spellcasting_progression ON subclass_spellcasting(progression_slug);
