BEGIN;

-- Generated by tools/generate_imports.py
-- Source: /home/lucaslima/Projetos/container-lucas/dnd/public/base
-- D&D 2024 class and subclass catalog.

CREATE TEMP TABLE _import_class_data (
    name TEXT PRIMARY KEY,
    hit_die TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO _import_class_data (name, hit_die) VALUES
    ('Barbarian', 'd12'),
    ('Bard', 'd8'),
    ('Cleric', 'd8'),
    ('Druid', 'd8'),
    ('Fighter', 'd10'),
    ('Monk', 'd8'),
    ('Paladin', 'd10'),
    ('Ranger', 'd10'),
    ('Rogue', 'd8'),
    ('Sorcerer', 'd6'),
    ('Warlock', 'd8'),
    ('Wizard', 'd6');

INSERT INTO classes (name, hit_die)
SELECT name, hit_die
FROM _import_class_data
ON CONFLICT (name) DO UPDATE SET hit_die = EXCLUDED.hit_die;

CREATE TEMP TABLE _import_subclass_data (
    class_name TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    PRIMARY KEY (class_name, name)
) ON COMMIT DROP;

INSERT INTO _import_subclass_data (class_name, name, description) VALUES
    ('Barbarian', 'Path of the Berserker', 'Barbarians who walk the Path of the Berserker direct their Rage primarily toward violence. Their path is one of untrammeled fury, and they thrill in the chaos of battle as they allow their Rage to seize and empower them.'),
    ('Barbarian', 'Path of the Wild Heart', 'Barbarians who walk the Path of the Wild Heart find that their Rage connects them to the natural world. When you enter your Rage, you channel the power of beasts, gaining supernatural options to aid you in combat.'),
    ('Barbarian', 'Path of the World Tree', 'Barbarians who follow the Path of the World Tree draw on the cosmic vitality of Yggdrasil. While raging, they can manifest spectral roots and branches to protect allies, teleport across the battlefield, and strike foes from afar.'),
    ('Barbarian', 'Path of the Zealot', 'Barbarians who walk the Path of the Zealot are fueled by a divine fury that drives them into battle. They channel the power of gods to strike their enemies, protect their allies, and conquer death itself.'),
    ('Bard', 'College of Dance', 'Bards who express their magic through graceful movement and combat agility.'),
    ('Bard', 'College of Glamour', 'Masters of the Feywild''s beauty, weaving illusions and charms to enthrall others.'),
    ('Bard', 'College of Lore', 'Masters of knowledge and versatile magic.'),
    ('Bard', 'College of Valor', 'Combat-focused bards who inspire heroics on the front lines of battle.'),
    ('Cleric', 'Life Domain', 'Specializes in the preservation of life and mastery of healing magic.'),
    ('Cleric', 'Light Domain', 'Wielders of radiant energy and holy fire to reveal truths and destroy evil.'),
    ('Cleric', 'Trickery Domain', 'Agents of chaos and deception, using illusions to outwit foes.'),
    ('Cleric', 'War Domain', 'Holy warriors who lead from the front, inspiring martial excellence.'),
    ('Druid', 'Circle of the Land', 'Druids who draw power from a specific type of terrain, gaining versatile spells and recovery.'),
    ('Druid', 'Circle of the Moon', 'Masters of Wild Shape who can transform into powerful beasts and move with lunar agility.'),
    ('Druid', 'Circle of the Sea', 'Druids who command the wrath of the ocean, moving with aquatic ease and storm speed.'),
    ('Druid', 'Circle of the Stars', 'Astromancers who channel the constellations to empower their spells and forms.'),
    ('Fighter', 'Battle Master', 'Masters of martial techniques and battlefield control using maneuvers.'),
    ('Fighter', 'Champion', 'Paragons of physical excellence, focusing on raw power and devastating critical hits.'),
    ('Fighter', 'Eldritch Knight', 'Combine martial prowess with arcane magic to overwhelm foes.'),
    ('Fighter', 'Psi Warrior', 'Awaken psionic power to enhance attacks and protect allies.'),
    ('Monk', 'Warrior of Mercy', 'Healers and harbingers of death who balance the scales of life.'),
    ('Monk', 'Warrior of Shadow', 'Ninja-like warriors who use shadows and deception to strike from the dark.'),
    ('Monk', 'Warrior of the Elements', 'Masters of the primal forces, weaving elemental energy into their strikes.'),
    ('Monk', 'Warrior of the Open Hand', 'Ultimate masters of martial arts combat, focusing on controlling the flow of battle.'),
    ('Paladin', 'Oath of Devotion', 'The original paladin oath, focusing on justice, virtue, and order.'),
    ('Paladin', 'Oath of Glory', 'Warriors who believe they are destined for greatness and legendary deeds.'),
    ('Paladin', 'Oath of the Ancients', 'Protectors of the light and the natural world.'),
    ('Paladin', 'Oath of Vengeance', 'Relentless hunters who seek to punish those who have committed great evils.'),
    ('Ranger', 'Beast Master', 'Rangers who form a deep bond with a primal animal companion.'),
    ('Ranger', 'Fey Wanderer', 'Rangers who represent the border between the material world and the Feywild.'),
    ('Ranger', 'Gloom Stalker', 'Masters of the dark, hunting foes in caves and the Underdark.'),
    ('Ranger', 'Hunter', 'Specialized hunters who focus on taking down specific types of threats.'),
    ('Rogue', 'Arcane Trickster', 'Rogues who combine fine-fingered legerdemain with the magical power of illusion and enchantment.'),
    ('Rogue', 'Assassin', 'Masters of disguise, poison, and the quick, lethal kill.'),
    ('Rogue', 'Soulknife', 'Psionically gifted rogues who manifest blades of pure psychic energy.'),
    ('Rogue', 'Thief', 'Rogues who master mobility and using the tools at hand.'),
    ('Sorcerer', 'Aberrant Sorcery', 'Magic derived from an alien influence or psionic power.'),
    ('Sorcerer', 'Clockwork Sorcery', 'Magic from the plane of Mechanus, embodying order and balance.'),
    ('Sorcerer', 'Draconic Sorcery', 'Your magic comes from a draconic ancestor.'),
    ('Sorcerer', 'Wild Magic Sorcery', 'Your magic comes from the wild forces of chaos.'),
    ('Warlock', 'Archfey Patron', 'Your patron is a lord or lady of the Feywild.'),
    ('Warlock', 'Celestial Patron', 'Your patron is a powerful being of the Upper Planes.'),
    ('Warlock', 'Fiend Patron', 'Your patron is a powerful fiend from the lower planes.'),
    ('Warlock', 'Great Old One Patron', 'Your patron is a mysterious entity from the Far Realm or the depths of space.'),
    ('Wizard', 'Abjurer', 'Focuses on spells that block, banish, and protect.'),
    ('Wizard', 'Diviner', 'Focuses on spells that reveal information and foresee the future.'),
    ('Wizard', 'Evoker', 'Focuses on spells that create powerful elemental effects.'),
    ('Wizard', 'Illusionist', 'Focuses on spells that deceive the senses and minds of others.');

INSERT INTO subclasses (class_id, name, description)
SELECT c.id, sd.name, sd.description
FROM _import_subclass_data sd
JOIN classes c ON c.name = sd.class_name
ON CONFLICT (class_id, name) DO UPDATE SET description = EXCLUDED.description;

COMMIT;
